'use strict';
const byId=id=>document.getElementById(id),keys=['homeScore','awayScore','homeSets','awaySets'];
let config={regions:{},polarity:'light',confidence:70,setsEnabled:false,device:''};
try{const c=JSON.parse(localStorage.getItem('htv-volleyball-camera')||'{}');config={...config,...c,regions:c.regions||{}}}catch(e){}
let stream=null,worker=null,loading=null,busy=false,running=false,generation=0,selected=null,drag=null,lastTest=null,verified=false;
let candidates={};const video=byId('video'),overlay=byId('overlay'),ctx=overlay.getContext('2d');
const palette={homeScore:'#36d0ff',awayScore:'#ffb63b',homeSets:'#70ed9a',awaySets:'#e79bff'};
function status(text){byId('status').textContent=text}
function store(){localStorage.setItem('htv-volleyball-camera',JSON.stringify(config))}
function parseReading(key,text){const clean=String(text).replace(/\s/g,'');if(!/^\d{1,2}$/.test(clean))return null;const n=Number(clean);return n<=(key.endsWith('Sets')?9:99)?n:null}
function format(key,value){return value===null?'—':String(value)}
function activeKeys(){return config.setsEnabled?keys:keys.slice(0,2)}
function ready(){return stream&&video.readyState>=2&&activeKeys().every(k=>config.regions[k])}
function buttons(){byId('test').disabled=!ready()||busy||running;byId('start').disabled=!ready()||busy||running||!verified;byId('pause').disabled=!running;byId('apply').disabled=running||busy||!lastTest||!activeKeys().every(k=>Number.isInteger(lastTest[k]?.value));byId('disconnect').disabled=!stream;byId('connect').disabled=busy||running}
function pause(message='Automatic updates paused.'){running=false;generation++;candidates={};buttons();status(message)}
function invalidate(){pause('Reading areas changed. Test the readings before starting.');verified=false;lastTest=null;buttons()}
function point(event){const b=overlay.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(event.clientX-b.left)/b.width)),y:Math.max(0,Math.min(1,(event.clientY-b.top)/b.height))}}
function renderBoxes(){if(!video.videoWidth)return;overlay.width=video.videoWidth;overlay.height=video.videoHeight;ctx.clearRect(0,0,overlay.width,overlay.height);const regions={...config.regions};if(drag)regions[selected]={x:Math.min(drag.start.x,drag.end.x),y:Math.min(drag.start.y,drag.end.y),w:Math.abs(drag.end.x-drag.start.x),h:Math.abs(drag.end.y-drag.start.y)};for(const [key,r] of Object.entries(regions)){if(!keys.includes(key))continue;ctx.strokeStyle=palette[key];ctx.lineWidth=3;ctx.strokeRect(r.x*overlay.width,r.y*overlay.height,r.w*overlay.width,r.h*overlay.height);ctx.fillStyle=palette[key];ctx.font='bold 18px Arial';ctx.fillText(({homeScore:'Top team points',awayScore:'Bottom team points',homeSets:'Top team sets won',awaySets:'Bottom team sets won'})[key],r.x*overlay.width+4,Math.max(20,r.y*overlay.height-6))}}
overlay.addEventListener('pointerdown',event=>{if(!selected||!stream)return;invalidate();overlay.setPointerCapture(event.pointerId);drag={start:point(event),end:point(event)};renderBoxes()});
overlay.addEventListener('pointermove',event=>{if(drag){drag.end=point(event);renderBoxes()}});
overlay.addEventListener('pointerup',event=>{if(!drag)return;drag.end=point(event);const r={x:Math.min(drag.start.x,drag.end.x),y:Math.min(drag.start.y,drag.end.y),w:Math.abs(drag.end.x-drag.start.x),h:Math.abs(drag.end.y-drag.start.y)};if(r.w>.008&&r.h>.008){config.regions[selected]=r;store();status('Area saved. Select the next area or click Test reading.')}drag=null;renderBoxes();buttons()});
overlay.addEventListener('pointercancel',()=>{drag=null;renderBoxes()});
for(const button of document.querySelectorAll('[data-region]'))button.onclick=()=>{selected=button.dataset.region;for(const b of document.querySelectorAll('[data-region]'))b.classList.toggle('active',b===button);status('Drag a box around '+button.textContent.toLowerCase()+'.')};
async function connect(){pause();verified=false;lastTest=null;buttons();try{if(!navigator.mediaDevices?.getUserMedia)throw Error('Camera access is unavailable. Open this page in Chrome using the HTTPS link.');if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;const requested=byId('device').value;stream=await navigator.mediaDevices.getUserMedia({audio:false,video:{...(requested?{deviceId:{exact:requested}}:{}),width:{ideal:1920},height:{ideal:1080}}});video.srcObject=stream;await video.play();const devices=await navigator.mediaDevices.enumerateDevices();byId('device').replaceChildren();for(const d of devices.filter(d=>d.kind==='videoinput')){const o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||'Camera '+(byId('device').options.length+1);byId('device').appendChild(o)}const actual=stream.getVideoTracks()[0].getSettings().deviceId;byId('device').value=actual||requested;config.device=byId('device').value;store();renderBoxes();status('Camera connected. Mark the points and, if enabled, both sets won, then test.');stream.getVideoTracks()[0].addEventListener('ended',()=>disconnect('Camera disconnected. Updates paused.'))}catch(e){status(e.name==='NotAllowedError'?'Camera permission denied. Allow camera access in your browser and try again.':e.message);stream=null}buttons()}
function disconnect(message='Camera disconnected.'){pause(message);if(stream)stream.getTracks().forEach(t=>t.stop());stream=null;video.srcObject=null;verified=false;lastTest=null;ctx.clearRect(0,0,overlay.width,overlay.height);buttons()}
async function engine(){if(worker)return worker;if(!window.Tesseract)throw Error('The reading engine did not load. Check your internet connection and reload this page.');if(!loading)loading=(async()=>{status('Loading reading engine for first use…');const w=await Tesseract.createWorker('eng',1,{logger:m=>{if(m.status?.includes('loading')||m.status?.includes('initializing'))status('Loading reading engine… '+Math.round((m.progress||0)*100)+'%')}});await w.setParameters({tessedit_char_whitelist:'0123456789:',tessedit_pageseg_mode:Tesseract.PSM.SINGLE_LINE,user_defined_dpi:'150'});worker=w;return w})().catch(e=>{loading=null;throw e});return loading}
function crop(frame,r){const sw=Math.max(1,Math.round(r.w*frame.width)),sh=Math.max(1,Math.round(r.h*frame.height)),scale=Math.min(6,Math.max(2,100/sh)),pad=15;const c=document.createElement('canvas');c.width=Math.round(sw*scale)+pad*2;c.height=Math.round(sh*scale)+pad*2;const x=c.getContext('2d',{willReadFrequently:true});x.fillStyle='white';x.fillRect(0,0,c.width,c.height);x.drawImage(frame,r.x*frame.width,r.y*frame.height,sw,sh,pad,pad,c.width-pad*2,c.height-pad*2);if(config.polarity!=='original'){const image=x.getImageData(pad,pad,c.width-pad*2,c.height-pad*2),p=image.data;let lo=255,hi=0;for(let i=0;i<p.length;i+=4){const v=Math.max(p[i],p[i+1],p[i+2]);lo=Math.min(lo,v);hi=Math.max(hi,v)}for(let i=0;i<p.length;i+=4){let v=255*(Math.max(p[i],p[i+1],p[i+2])-lo)/Math.max(1,hi-lo);if(config.polarity==='light')v=255-v;p[i]=p[i+1]=p[i+2]=v}x.putImageData(image,pad,pad)}return c}
async function scan(){if(!ready())throw Error('Connect a camera and mark every enabled reading area first.');const w=await engine(),frame=document.createElement('canvas');frame.width=video.videoWidth;frame.height=video.videoHeight;frame.getContext('2d').drawImage(video,0,0);const result={};for(const key of activeKeys()){const image=crop(frame,config.regions[key]);const preview=byId(key+'Crop');preview.src=image.toDataURL('image/png');preview.hidden=false;const {data}=await w.recognize(image);const parsed=parseReading(key,data.text);const confidence=Number(data.confidence)||0;result[key]={value:confidence>=config.confidence?parsed:null,text:data.text.trim(),confidence};byId(key+'Value').textContent=format(key,result[key].value);byId(key+'Note').textContent=result[key].value===null?'Uncertain: '+(data.text.trim()||'no digits')+' ('+Math.round(confidence)+'%)':Math.round(confidence)+'% confidence'}return result}
function stable(key,value,time){if(value===null){delete candidates[key];return false}const previous=candidates[key];candidates[key]={value,time,count:previous&&previous.value===value?(previous.count||1)+1:1};return candidates[key].count>=2}
function readState(){try{return {homeScore:0,awayScore:0,homeSets:0,awaySets:0,...JSON.parse(localStorage.getItem('htv-volleyball-score')||'{}')}}catch(e){return {homeScore:0,awayScore:0,homeSets:0,awaySets:0}}}
function apply(result,automatic){const state=readState(),time=Date.now();let changed=false;for(const key of activeKeys()){const value=result[key]?.value??null;if(value===null)continue;if(automatic&&!stable(key,value,time))continue;if(automatic&&Math.abs(value-state[key])>1){status('A large score change was held. Pause and verify it, then Apply this reading once.');continue}if(state[key]!==value){state[key]=value;changed=true}}if(changed){state.stamp=time;localStorage.setItem('htv-volleyball-score',JSON.stringify(state));byId('status').textContent='Updated overlay at '+new Date().toLocaleTimeString()}return changed}
async function test(){if(busy)return;busy=true;buttons();const token=generation;try{const result=await scan();if(token!==generation)return;lastTest=result;verified=activeKeys().every(k=>Number.isInteger(result[k]?.value));status(verified?'Check these numbers against the gym scoreboard. If correct, start automatic updates.':'A reading is uncertain. Adjust the camera or boxes, then test again.')}catch(e){verified=false;status(e.message)}finally{busy=false;buttons()}}
async function start(){if(!verified||!ready()||busy)return;running=true;candidates={};const token=++generation;buttons();status('Automatic updates on. Confirming two readings…');while(running&&token===generation){busy=true;try{const result=await scan();if(!running||token!==generation)break;apply(result,true);if(activeKeys().some(k=>result[k].value===null))status('Reading uncertain — keeping the last confirmed numbers.')}catch(e){pause('Updates paused: '+e.message);break}finally{busy=false;buttons()}await new Promise(resolve=>setTimeout(resolve,350))}}
byId('connect').onclick=connect;byId('disconnect').onclick=()=>disconnect();byId('test').onclick=test;byId('start').onclick=start;byId('pause').onclick=()=>pause();byId('apply').onclick=()=>{if(lastTest&&!running)apply(lastTest,false)};
byId('clear').onclick=()=>{invalidate();config.regions={};store();renderBoxes();buttons()};
for(const key of ['polarity','confidence','setsEnabled']){const input=byId(key);if(key==='setsEnabled')input.checked=config[key];else input.value=config[key];input.onchange=()=>{invalidate();config[key]=key==='setsEnabled'?input.checked:key==='confidence'?Number(input.value):input.value;store();buttons()}}
byId('device').onchange=()=>{config.regions={};invalidate();if(stream)disconnect('Camera changed. Click Start camera and mark the new picture.');store()};
window.addEventListener('beforeunload',()=>{running=false;if(stream)stream.getTracks().forEach(t=>t.stop());if(worker)worker.terminate()});
buttons();

